### ISSUE TITLE
Should I completely trust the formal validator ? 

### ISSUE THREAD

**Issue by rknath** [eschkufz/stoke-release#10]
How good is the current implementation of formal verification ? 
Is stoke dependent upon representative testcases anyhow?

**Comment by bchurchill** [comment]
*We have tested the former validator's circuits against the hardware 
with a fuzzing tool.*  You can run it with "make test" and the 
environment variable "TEST_VALIDATOR_FUZZ_COUNT" controls how many 
iterations it does (default is only 100).  There are also several other 
testcases we've written for individual instructions.

At this point, we don't see bugs reported by the fuzzer, even though we 
run 30,000 iterations automatically whenever we push code to our 
development repository.  So, the remaining bugs are likely corner cases 
for specific instructions -- but we haven't searched for these, so they 
probably exist.  As a result, for research purposes, ***I think the 
validator is pretty good***.  I wouldn't recommend it for production 
without additional testing for your particular use case.  *Don't use it 
for anything that's mission-critical, obviously; and we're in no way 
liable for how you use it.*

***The major exception is memory***.  That support is new and has known 
bugs when it comes to checking alignment in SSE instructions. There are 
lots of limitations to how we support memory, and those are documented 
(see the validator readme).  But if your examples don't have memory it's 
fairly stable.

In general, the validator is good about giving you an error message when 
something isn't supported -- and that's a lot.  Obviously we don't 
handle loops. ***There's a README.md file in the validator directory*** 
that details this more.

Lastly -- ***stoke isn't dependent on representative testcases***, so 
long as the validator supports your code.  The examples/parity directory 
demonstrates this.  We start stoke with no testcases at all, and use the 
validator to iteratively build them with counterexamples.

If you find bugs, ***give us the full details***, so we can take a 
look.  Since the memory support is experimental, we might not address 
those, but if you find a bug that doesn't involve memory we'll 
definitely fix it.

We aren't

**Comment by rknath** [comment]
Churchill, 
Thanks a lot for very detailed and informative response. 

I started trying to implement couple of instructions. I went through the README.md in validator directory ... its very detailed and useful.  

Few question regarding that .. 

1. How do I validate that my implementation of a circuit is correct? 
    Which TEST_F do I need to use ? I see different test cases in  tests/validator/handlers/. Some of them are probably written as bug appeared and reused as equivalent instruction sequence found. Is there a single kind of TEST_F that may do that job ? 
    Or I need to validate the circuit for generic case and all the possible corner cases  ? 

2. Do I need to cover all the operand scenario for the implemented instruction to make sure that validator (+test) and stoke is working correctly and consistently ? 

 for example ... 
  I want to implement pmovmskb instruction

  I added the opcode is added in  src/validator/handlers/ and implemented the circuit there. 

  Added a testcase in tests/validator/handlers/pmovmskb.h

  My instruction sequence has only pmovmskb %xmm0, %eax. I only implemented for this. Do I need to complete the implementation for other operand cases ?

**Comment by bchurchill** [comment]
1.  This depends on how much testing you want to do.  The easiest thing, which I often do, is to just use the fuzz tester, which should "just work".  Run it for a high number of iterations, and use "grep -A2" for the instruction you want in the output.  If there's no error message afterward, than it was checked on a random input state.  The more you fuzz test, the better chances you have of finding a bug.

Other than that, any tests you write will be specific to your instruction, and there's no generic way of doing this.  You can test as much or as little as you like to get to the confidence level of your choice.

2.  You don't have to implement all the cases.  There's a function in each handler that returns the support level for each instruction.  This should return 0 for a particular combination of operands if you don't support it; that way the validator will return the appropriate error message if it encounters an unsupported combination.  You should also check to make sure you support the instruction in the handler itself, and throw the VALIDATOR_ERROR macro if something bad happens (see the code for examples of this).

**Comment by rknath** [comment]
I hope I am not missing something very silly .... 

I deliberately wrote a wrong  implementation of pmovmskb. 
Only covering pmovmskb %xmm0, %eax case . 

For quick testing I have put it inside " src/validator/handlers/move_handler.h " 

    if( opcode == "pmovmskb" ){
        if (src.is_sse_register() and dst.is_gp_register() and src.size() == 128 and dst.size() == 32 ){ 
            cout <<"Handler for pmovmskb %sse128, %gp32 instruction --- \n" ;
            to_move =   SymBitVector::constant(dst.size(), 0x00000000)  ;
            ss.set(dst, to_move);
            return; 
        }
        else{
            throw VALIDATOR_ERROR("Only pmovmskb %sse128, %gp32 i mplemented");
        }
    }



get_support( ... returns SupportLevel::NONE for other operand scenario. 

VALIDATOR_ERROR is thrown from build_circuit( .... 


The handler gets called 15-20 times in the fuzz test. But there is no complain regarding error. 

[----------] * pmovmskb %xmm6, %r13d
Handler for pmovmskb %sse128, %gp32 instruction ---
[----------] * vroundpd $0x5, 0x64(%rsp,%rdx,8), %xmm12
[----------]   - No validator support



I also put a test case in /tests/validator/handlers/

TEST_F(ValidatorPmovmskbTest, HardwareTest1){

  target_ << "pmovmskb  %xmm0, %eax" << std::endl;
  target_ << "retq" << std::endl;

  stoke::Sandbox sb;
  sb.set_abi_check(false);
  stoke::StateGen sg(&sb);
  stoke::CpuState cs;
  sg.get(cs);
  cs.gp[x64asm::ax].get_fixed_quad(0)    = 0x0000000000000000;
  cs.sse[x64asm::ymm0].get_fixed_quad(0) = 0xffffffffffffffff;
  cs.sse[x64asm::ymm0].get_fixed_quad(1) = 0xffffffffffffffff;
  cs.sse[x64asm::ymm0].get_fixed_quad(2) = 0xffffffffffffffff;
  cs.sse[x64asm::ymm0].get_fixed_quad(3) = 0xffffffffffffffff;
  set_live_outs(x64asm::RegSet::empty()  + x64asm::rax);
  check_circuit(cs);
}

I thought this one should give error. 

This one passes too.


[----------] 4 tests from ValidatorPmovmskbTest
[ RUN      ] ValidatorPmovmskbTest.NotANoop
Handler for pmovmskb %sse128, %gp32 instruction ---
[       OK ] ValidatorPmovmskbTest.NotANoop (40 ms)
[ RUN      ] ValidatorPmovmskbTest.Identity
Handler for pmovmskb %sse128, %gp32 instruction ---
Handler for pmovmskb %sse128, %gp32 instruction ---
[       OK ] ValidatorPmovmskbTest.Identity (26 ms)
[ RUN      ] ValidatorPmovmskbTest.LooksCorrect
Handler for pmovmskb %sse128, %gp32 instruction ---
[       OK ] ValidatorPmovmskbTest.LooksCorrect (6 ms)
[ RUN      ] ValidatorPmovmskbTest.HardwareTest1
Handler for pmovmskb %sse128, %gp32 instruction ---
[       OK ] ValidatorPmovmskbTest.HardwareTest1 (7 ms)
[----------] 4 tests from ValidatorPmovmskbTest (79 ms total)


Am I missing some obvious steps ?

**Comment by bchurchill** [comment]
I can't think of anything you're missing, but this looks pretty bad.  If you were missing something those tests still shouldn't pass.  Try doing 'make dist_clean' and then rebuilding to make sure this is still happening.  Sometimes our build system messes things up.  If you send me the actual code you used (e.g. as a diff) I can take a look at it in more detail.

**Comment by bchurchill** [comment]
Can you confirm if you're still having this problem after a 'make dist_clean' followed by 'make test' ?

**Comment by rknath** [comment]
I tried make dist_clean and was getting similar error. 
I don't have access to the machine now. I will paste the "git diff" here. 
Sorry for the delay ( I know I am supposed to provide some other things ).

**Comment by rknath** [comment]
diff --git a/Makefile b/Makefile
index 4f2e235..a2ace67 100644
--- a/Makefile
+++ b/Makefile
@@ -14,7 +14,7 @@
 
 ##### CONSTANT DEFINITIONS
 
-CXX=ccache g++ -std=c++11 -Werror -Wextra -Wfatal-errors
+CXX=g++ -std=c++11 -Werror -Wextra -Wfatal-errors
 
 INC_FOLDERS=\
                                                ./ \
@@ -71,6 +71,7 @@ SRC_OBJ=\
        src/validator/handlers/lea_handler.o   \
        src/validator/handlers/move_handler.o  \
        src/validator/handlers/packed_handler.o \
+       src/validator/handlers/packed_shift_handler.o \
        src/validator/handlers/shift_handler.o \
        src/validator/handlers/simple_handler.o \
        \
@@ -198,12 +199,14 @@ src/ext/astyle:
        $(MAKE) -C src/ext/astyle/build/gcc -j8
 
 src/ext/cpputil:
-       git clone git://github.com/eschkufz/cpputil.git src/ext/cpputil && \
+       #git clone git://github.com/eschkufz/cpputil.git src/ext/cpputil && 
+       git clone https://github.com/eschkufz/cpputil src/ext/cpputil && \
        cd src/ext/cpputil && \
        git checkout -b e7b99c1
 
 src/ext/x64asm:
-       git clone git://github.com/eschkufz/x64asm.git src/ext/x64asm && \
+       #git clone git://github.com/eschkufz/x64asm.git src/ext/x64asm && 
+       git clone https://github.com/eschkufz/x64asm src/ext/x64asm && \
        cd src/ext/x64asm && \
        git checkout -b 0ed4faf
 
diff --git a/examples/pairity/Makefile b/examples/pairity/Makefile
index 2906250..153051e 100644
--- a/examples/pairity/Makefile
+++ b/examples/pairity/Makefile
@@ -12,7 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-all: orig extract testcase search replace
+all: orig extract search replace
 
 orig:
        g++ -std=c++11 -fno-inline -O3 main.cc
diff --git a/examples/tutorial/search.conf b/examples/tutorial/search.conf
index c3e83b0..c05824a 100644
--- a/examples/tutorial/search.conf
+++ b/examples/tutorial/search.conf
@@ -40,4 +40,4 @@
 --timeout_action testcase # Try adding a new testcase from the testset when search times out
 --timeout_cycles 16 # Timeout up to 16 times before giving up
 
---strategy hold_out # Verify results using a larger hold out testcase set
+--strategy formal #hold_out # Verify results using a larger hold out testcase set
diff --git a/src/validator/handlers/move_handler.cc b/src/validator/handlers/move_handler.cc
index 7293334..1a53edf 100644
--- a/src/validator/handlers/move_handler.cc
+++ b/src/validator/handlers/move_handler.cc
@@ -12,9 +12,16 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-
+#define V_UPDATE 
 #include "src/validator/handlers/move_handler.h"
 
+#ifdef V_UPDATE
+#include <map>
+#include <functional>
+#include "src/validator/handler.h"
+#include "src/validator/error.h"
+#endif 
+
 using namespace stoke;
 using namespace x64asm;
 using namespace std;
@@ -41,11 +48,12 @@ const map<string, bool> MoveHandler::sign_extend_ = {
 Handler::SupportLevel MoveHandler::get_support(const Instruction& instr) {
   string opcode = get_opcode(instr);
 
-
-  if (sign_extend_.find(opcode) == sign_extend_.end())
+  if (sign_extend_.find(opcode) == sign_extend_.end()){ 
     return SupportLevel::NONE;
-  else
+  }  
+  else{ 
     return (Handler::SupportLevel)(SupportLevel::BASIC | SupportLevel::CEG);
+  }
 }
 
 void MoveHandler::build_circuit(const Instruction& instr, SymState& ss) {
diff --git a/src/validator/handlers/packed_handler.h b/src/validator/handlers/packed_handler.h
index b314b29..420530b 100644
--- a/src/validator/handlers/packed_handler.h
+++ b/src/validator/handlers/packed_handler.h
@@ -20,7 +20,6 @@
 #include <functional>
 
 #include "src/validator/handler.h"
-
 namespace stoke {
 
 /** For instructions that repeat the same instruction across multiple data in
@@ -166,6 +165,10 @@ public:
              f(a[31][0],  a[63][32]);
     }, 128, 128, true);
 
+    add_opcode("pmovmskb", [](SymBitVector a, SymBitVector b) {
+      return b;  
+    }, 0);
+ 
     add_opcode("hsubpd", [] (SymBitVector a, SymBitVector b) {
       SymFunction f("sub_double", 64, {64, 64});
       return f(b[63][0], b[127][64]) || f(a[63][0], a[127][64]);
@@ -746,6 +749,18 @@ private:
     }
 
     SymBitVector operator()(x64asm::Operand arg1, SymBitVector bv1, x64asm::Operand arg2, SymBitVector bv2, SymState& ss) {
+      if(opcode_ == "pmovmskb" ){
+        if (arg2.is_sse_register() and arg1.is_gp_register() and arg2.size() == 128 and arg1.size() == 32 ){ // pmovmskb %xmm7, %edx
+            std::cout <<"Handler for pmovmskb %sse128, %gp32 instruction --- "<< arg1.size() <<" " << arg2.size() << " " ; 
+            std::cout <<  " \n";
+            return bv2; 
+        }
+        else{
+            throw VALIDATOR_ERROR("Only pmovmskb %sse128, %gp32 implemented");
+        }
+      }
+      else 
+
       return binop_(bv1, bv2);
     }
 
diff --git a/src/validator/handlers/shift_handler.cc b/src/validator/handlers/shift_handler.cc
index 9895e3c..044d51e 100644
--- a/src/validator/handlers/shift_handler.cc
+++ b/src/validator/handlers/shift_handler.cc
@@ -51,7 +51,7 @@ const map<string, array<bool, 4>> ShiftHandler::to_right_sign_rotate_cf_ = {
   { "rcrb", {true, false, true, true} },
   { "rcrw", {true, false, true, true} },
   { "rcrl", {true, false, true, true} },
-  { "rcrq", {true, false, true, true} },
+  { "rcrq", {true, false, true, true} }
 };
 
 
@@ -90,7 +90,6 @@ void ShiftHandler::build_circuit(const x64asm::Instruction& instr, SymState& sta
 
   Operand dest = instr.get_operand<Operand>(0);
   Operand shift = instr.get_operand<Operand>(1);
-
   assert(dest.size() >= 8);
 
   // Mask 5 bits for <= 32-bits in operand, and 6 bits otherwise
diff --git a/tests/validator/handlers/xorps.h b/tests/validator/handlers/xorps.h
index 6999a93..6c2f165 100644
--- a/tests/validator/handlers/xorps.h
+++ b/tests/validator/handlers/xorps.h
@@ -70,3 +70,25 @@ TEST_F(ValidatorXorpsTest, XorCommutative) {
   assert_equiv();
 
 }
+
+TEST_F(ValidatorXorpsTest, HardwareTest1) {
+
+  target_ << "xorps  %xmm0, %xmm1" << std::endl;  // A     A+B
+  target_ << "retq" << std::endl;
+
+  stoke::Sandbox sb;
+  sb.set_abi_check(false);
+  stoke::StateGen sg(&sb);
+  stoke::CpuState cs;
+  sg.get(cs);
+  cs.sse[x64asm::ymm0].get_fixed_quad(0) = 0xffffffffffffffff;
+  cs.sse[x64asm::ymm0].get_fixed_quad(1) = 0xffffffffffffffff;
+  cs.sse[x64asm::ymm0].get_fixed_quad(2) = 0xffffffffffffffff;
+  cs.sse[x64asm::ymm0].get_fixed_quad(3) = 0xffffffffffffffff;
+  cs.sse[x64asm::ymm1].get_fixed_quad(0) = 0x0000000000000000;
+  cs.sse[x64asm::ymm1].get_fixed_quad(1) = 0x0000000000000000;
+  cs.sse[x64asm::ymm1].get_fixed_quad(2) = 0x0000000000000000;
+  cs.sse[x64asm::ymm1].get_fixed_quad(3) = 0x0000000000000000;
+  set_live_outs(x64asm::RegSet::empty()  + x64asm::xmm1);
+  check_circuit(cs);
+}

**Comment by rknath** [comment]
Hello ,
Please find the git diff and the test case attached.
thanks
r

On Sat, Jan 31, 2015 at 3:42 PM, Berkeley Churchill <
notifications@github.com> wrote:

> Can you confirm if you're still having this problem after a 'make
> dist_clean' followed by 'make test' ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eschkufz/stoke-release/issues/10#issuecomment-72342952>
> .
>



-- 
Rajib Nath
PhD Student, UCSD
http://cseweb.ucsd.edu/~rknath/
diff --git a/Makefile b/Makefile
index 4f2e235..a2ace67 100644
--- a/Makefile
+++ b/Makefile
@@ -14,7 +14,7 @@
 
 ##### CONSTANT DEFINITIONS
 
-CXX=ccache g++ -std=c++11 -Werror -Wextra -Wfatal-errors
+CXX=g++ -std=c++11 -Werror -Wextra -Wfatal-errors
 
 INC_FOLDERS=\
                                                ./ \
@@ -71,6 +71,7 @@ SRC_OBJ=\
        src/validator/handlers/lea_handler.o   \
        src/validator/handlers/move_handler.o  \
        src/validator/handlers/packed_handler.o \
+       src/validator/handlers/packed_shift_handler.o \
        src/validator/handlers/shift_handler.o \
        src/validator/handlers/simple_handler.o \
        \
@@ -198,12 +199,14 @@ src/ext/astyle:
        $(MAKE) -C src/ext/astyle/build/gcc -j8
 
 src/ext/cpputil:
-       git clone git://github.com/eschkufz/cpputil.git src/ext/cpputil && \
+       #git clone git://github.com/eschkufz/cpputil.git src/ext/cpputil && 
+       git clone https://github.com/eschkufz/cpputil src/ext/cpputil && \
        cd src/ext/cpputil && \
        git checkout -b e7b99c1
 
 src/ext/x64asm:
-       git clone git://github.com/eschkufz/x64asm.git src/ext/x64asm && \
+       #git clone git://github.com/eschkufz/x64asm.git src/ext/x64asm && 
+       git clone https://github.com/eschkufz/x64asm src/ext/x64asm && \
        cd src/ext/x64asm && \
        git checkout -b 0ed4faf
 
diff --git a/examples/pairity/Makefile b/examples/pairity/Makefile
index 2906250..153051e 100644
--- a/examples/pairity/Makefile
+++ b/examples/pairity/Makefile
@@ -12,7 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-all: orig extract testcase search replace
+all: orig extract search replace
 
 orig:
        g++ -std=c++11 -fno-inline -O3 main.cc
diff --git a/examples/tutorial/search.conf b/examples/tutorial/search.conf
index c3e83b0..c05824a 100644
--- a/examples/tutorial/search.conf
+++ b/examples/tutorial/search.conf
@@ -40,4 +40,4 @@
 --timeout_action testcase # Try adding a new testcase from the testset when search times out
 --timeout_cycles 16 # Timeout up to 16 times before giving up
 
---strategy hold_out # Verify results using a larger hold out testcase set
+--strategy formal #hold_out # Verify results using a larger hold out testcase set
diff --git a/src/validator/handlers/move_handler.cc b/src/validator/handlers/move_handler.cc
index 7293334..1a53edf 100644
--- a/src/validator/handlers/move_handler.cc
+++ b/src/validator/handlers/move_handler.cc
@@ -12,9 +12,16 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-
+#define V_UPDATE 
 #include "src/validator/handlers/move_handler.h"
 
+#ifdef V_UPDATE
+#include <map>
+#include <functional>
+#include "src/validator/handler.h"
+#include "src/validator/error.h"
+#endif 
+
 using namespace stoke;
 using namespace x64asm;
 using namespace std;
@@ -41,11 +48,12 @@ const map<string, bool> MoveHandler::sign_extend_ = {
 Handler::SupportLevel MoveHandler::get_support(const Instruction& instr) {
   string opcode = get_opcode(instr);
 
-
-  if (sign_extend_.find(opcode) == sign_extend_.end())
+  if (sign_extend_.find(opcode) == sign_extend_.end()){ 
     return SupportLevel::NONE;
-  else
+  }  
+  else{ 
     return (Handler::SupportLevel)(SupportLevel::BASIC | SupportLevel::CEG);
+  }
 }
 
 void MoveHandler::build_circuit(const Instruction& instr, SymState& ss) {
diff --git a/src/validator/handlers/packed_handler.h b/src/validator/handlers/packed_handler.h
index b314b29..420530b 100644
--- a/src/validator/handlers/packed_handler.h
+++ b/src/validator/handlers/packed_handler.h
@@ -20,7 +20,6 @@
 #include <functional>
 
 #include "src/validator/handler.h"
-
 namespace stoke {
 
 /** For instructions that repeat the same instruction across multiple data in
@@ -166,6 +165,10 @@ public:
              f(a[31][0],  a[63][32]);
     }, 128, 128, true);
 
+    add_opcode("pmovmskb", [](SymBitVector a, SymBitVector b) {
+      return b;  
+    }, 0);
+ 
     add_opcode("hsubpd", [] (SymBitVector a, SymBitVector b) {
       SymFunction f("sub_double", 64, {64, 64});
       return f(b[63][0], b[127][64]) || f(a[63][0], a[127][64]);
@@ -746,6 +749,18 @@ private:
     }
 
     SymBitVector operator()(x64asm::Operand arg1, SymBitVector bv1, x64asm::Operand arg2, SymBitVector bv2, SymState& ss) {
+      if(opcode_ == "pmovmskb" ){
+        if (arg2.is_sse_register() and arg1.is_gp_register() and arg2.size() == 128 and arg1.size() == 32 ){ // pmovmskb %xmm7, %edx
+            std::cout <<"Handler for pmovmskb %sse128, %gp32 instruction --- "<< arg1.size() <<" " << arg2.size() << " " ; 
+            std::cout <<  " \n";
+            return bv2; 
+        }
+        else{
+            throw VALIDATOR_ERROR("Only pmovmskb %sse128, %gp32 implemented");
+        }
+      }
+      else 
+
       return binop_(bv1, bv2);
     }
 
diff --git a/src/validator/handlers/shift_handler.cc b/src/validator/handlers/shift_handler.cc
index 9895e3c..044d51e 100644
--- a/src/validator/handlers/shift_handler.cc
+++ b/src/validator/handlers/shift_handler.cc
@@ -51,7 +51,7 @@ const map<string, array<bool, 4>> ShiftHandler::to_right_sign_rotate_cf_ = {
   { "rcrb", {true, false, true, true} },
   { "rcrw", {true, false, true, true} },
   { "rcrl", {true, false, true, true} },
-  { "rcrq", {true, false, true, true} },
+  { "rcrq", {true, false, true, true} }
 };
 
 
@@ -90,7 +90,6 @@ void ShiftHandler::build_circuit(const x64asm::Instruction& instr, SymState& sta
 
   Operand dest = instr.get_operand<Operand>(0);
   Operand shift = instr.get_operand<Operand>(1);
-
   assert(dest.size() >= 8);
 
   // Mask 5 bits for <= 32-bits in operand, and 6 bits otherwise
diff --git a/tests/validator/handlers/xorps.h b/tests/validator/handlers/xorps.h
index 6999a93..6c2f165 100644
--- a/tests/validator/handlers/xorps.h
+++ b/tests/validator/handlers/xorps.h
@@ -70,3 +70,25 @@ TEST_F(ValidatorXorpsTest, XorCommutative) {
   assert_equiv();
 
 }
+
+TEST_F(ValidatorXorpsTest, HardwareTest1) {
+
+  target_ << "xorps  %xmm0, %xmm1" << std::endl;  // A     A+B
+  target_ << "retq" << std::endl;
+
+  stoke::Sandbox sb;
+  sb.set_abi_check(false);
+  stoke::StateGen sg(&sb);
+  stoke::CpuState cs;
+  sg.get(cs);
+  cs.sse[x64asm::ymm0].get_fixed_quad(0) = 0xffffffffffffffff;
+  cs.sse[x64asm::ymm0].get_fixed_quad(1) = 0xffffffffffffffff;
+  cs.sse[x64asm::ymm0].get_fixed_quad(2) = 0xffffffffffffffff;
+  cs.sse[x64asm::ymm0].get_fixed_quad(3) = 0xffffffffffffffff;
+  cs.sse[x64asm::ymm1].get_fixed_quad(0) = 0x0000000000000000;
+  cs.sse[x64asm::ymm1].get_fixed_quad(1) = 0x0000000000000000;
+  cs.sse[x64asm::ymm1].get_fixed_quad(2) = 0x0000000000000000;
+  cs.sse[x64asm::ymm1].get_fixed_quad(3) = 0x0000000000000000;
+  set_live_outs(x64asm::RegSet::empty()  + x64asm::xmm1);
+  check_circuit(cs);
+}
rknath@scpbthsw55:/nfs/sc/proj/ssg/ubt

**Comment by bchurchill** [comment]
Thank you for the details.  I can confirm this looks like a bug in the testing system which I'm going to continue to investigate.

**Comment by bchurchill** [comment]
Do a 'git pull' followed by a 'make dist_clean'.

We just fixed the bug in the testing system.  In the process, we uncovered two minor bugs.  One affected the validator (it improperly handled a certain 32-bit override byte for memory references) and also one in the assembler (wrong assembly generated for movswl and movzwl when one operand is memory).  Your code now generates errors when you run the fuzz tester.

Anecdotally, this gives a pretty good impression of the stoke's overall stability.  In the past I've found that the fuzz tester reveals a bug in the assembler or sandbox about as often as we encounter a bug in the validator.  And, this is exactly what happened here.  Also, both of these bugs turned out to be memory-related.  Usually, we do find a few bugs like these when we improve our testing infrastructure; yet, most things work most of the time.

I'll close this ticket for now, since I think I've answered your questions and fixed some bugs.  You may open another ticket if you run into more issues.  Also, if you implement more circuits you're welcome to contribute them.  I don't know the mechanics of how we'll merge your changes into our repositories yet, but we can definitely work something out and recognize the contribution.

**Comment by rknath** [comment]
Thanks a lot. I will try and implement few instructions and will let you know how it goes.
