### ISSUE TITLE
Circuit Implementation - Detailed vs. BlackBox

### ISSUE THREAD

**Issue by rknath** [eschkufz/stoke-release#11]
I see many of the packed instructions are uninterpreted. 
Is it because of the time issue to implement ? 
Or to reduce formal validation time ?

**Comment by bchurchill** [comment]
It's both, actually, but mostly to reduce formal validation time.  We usually only do this for floating point.  Z3 and CVC4 tend to totally die when you implement a whole floating point instruction.  You might be able to get away with doing this for some small instructions yourself.

**Comment by rknath** [comment]
I got a follow up question ... 
so if my code has a mixture of instructions both 
- uninterpreted (Handler::BASIC) 
- and full support instructs( Handler::BASIC | Handler::CEG | Handler::ANALYSIS)

What kind of limitations the mix imposes up on search process? How much is it ?
is it mostly related to the uninterpreted ones ?

**Comment by bchurchill** [comment]
If you use uninterpreted functions we cannot get a counterexample (at 
least, currently).  This makes it harder to refine the search. Sometimes 
the search can get totally stuck if it doesn't have enough testcases and 
you're using uninterpreted functions.

**Comment by rknath** [comment]
I guess that's what I observed few times. Very obvious optimization wasn't found.
What plans do you have regarding it ?

**Comment by bchurchill** [comment]
We don't really have plans for this right now.  You're welcome to 
contribute!

**Comment by rknath** [comment]
I was wondering if parallellization(with accelerators) can be useful here. 
Stoke may have just hit the computation limit of traditional system.  Not sure how much parallelizable are the solvers. 

Is it doable to generate counter example for a code with uninterpreted functions? 

What if we use formal validation in conjuction with some testcases provided by the user? I guess it can't help forever. We can't provide inifnite amount of test cases.

**Comment by bchurchill** [comment]
I asked Rahul about some of these, and he mentioned that he and a new student of Alex, Wonyeol, are actually working on a validator for floating point.  I don't think we have plans to parallelize solvers, but others are working on this.

I personally don't know a general way of generating counterexamples if there are uninterpreted functions, but surely there are ways of doing this in special cases.  I don't think we have plans for this either, although it's crossed my mind to work on it.

You can use formal validation along with testcases.  As you say, this has a bounded benefit.
