### ISSUE TITLE
make test showing some error in Validation of circuit 

### ISSUE THREAD

**Issue by rknath** [eschkufz/stoke-release#13]
[  FAILED  ] ValidatorFuzzTest.RandomInstructionRandomState
[  FAILED  ] ValidatorPandnTest.LooksCorrect
[  FAILED  ] ValidatorPcmpeqbTest.OneMatch
[  FAILED  ] ValidatorPcmpeqbTest.WordMatch
[  FAILED  ] ValidatorPcmpeqbTest.SeveralMatch
[  FAILED  ] ValidatorXorpsTest.NotANoop
[  FAILED  ] ValidatorXorpsTest.SelfXorZero

**Comment by bchurchill** [comment]
These tests pass for us, so it's likely changes that you've introduced causing these errors.  All of the instructions listed here have their handlers implemented in packed_handler.cc / packed_handler.h, so if you've changed either of these files this could be the source of your problem.

**Comment by rknath** [comment]
yes.. I guess you are right ..

**Comment by rknath** [comment]
yes .. it rebuilding solved the issue.
