### ISSUE TITLE
Go support

### ISSUE THREAD

**Issue by ainar-g** [eschkufz/stoke-release#27]
I've tried using stoke on some binaries generated by [Go](https://golang.org/). The code can be found here: http://play.golang.org/p/ID0uimni3B. Here are the issues I've encountered:
1. Syntax errors:
   
   ```
    Error on line 0: syntax error, unexpected LABEL, expecting COLON
   ```
   
   Because of these errors a lot of files in bins (the folder with assembly files) are basically empty. This is solved by replacing `"."[a-zA-Z0-9]+` with `"."[a-zA-Z0-9_.(*)]+` in `src/ext/x64asm/src/att.l:108`. This makes stoke understand the Go method naming conventions (e.g. `pkg.(*Type).Method`). After that the errors that I get are like these:
   
   ```
   Error on line 0: syntax error, unexpected $end, expecting COLON
   Error on line 125: syntax error, unexpected R_32, expecting ENDL
   Error on line 6: Unable to parse instruction!
   ```
   
   Despite those I am able to proceed.
2. Deadlock? `stoke testcase` launches the program but after `main` finishes (judging by CPU consumption) it just gets stuck. Nothing is written to the testcase file and the command never exits, so I have to use `^C` to quit. It's a wild guess but it may have something to do with the fact that Go's calling convention is different from C's.
3. (Unrelated to Go). It seems like `--relax_reg` flag of `stoke search` is removed. Should be also removed from the docs.
- Additional info:
  Go version: 1.5.1.
  
  Commands used:
  
  ``` bash
  go build -o a.out popcnt.go
  stoke extract -i ./a.out -o bins
  stoke testcase --bin ./a.out -o test.tc --max_testcases 1024 --fxn main.popcnt
  ```
  
  `bins/main.popcnt.s` content:
  
  ``` as
  .text
  .globl main.popcnt
  .type main.popcnt, @function
  .main.popcnt:                  
  movq 0x8(%rsp), %rax   # 0   
  xorl %ecx, %ecx        # 1   
  cmpq $0x0, %rax        # 2   
  jbe .L_401023          # 3   
  .L_40100d:                     
  movq %rax, %rbx        # 4   
  andq $0x1, %rbx        # 5   
  addq %rcx, %rbx        # 6   
  movq %rbx, %rcx        # 7   
  shrq $0x1, %rax        # 8   
  cmpq $0x0, %rax        # 9   
  ja .L_40100d           # 10  
  .L_401023:                     
  movq %rcx, 0x10(%rsp)  # 11  
  retq                   # 12  
  addb %al, (%rax)       # 13  
  addb %al, (%rax)       # 14  
  addb %al, (%rax)       # 15  
  
  .size main.popcnt, .-main.popcnt
  ```
  
  `popcnt` disassembly as generated by `go build -gcflags '-S' popcnt.go`
  
  ``` asm
  "".popcnt t=1 size=48 value=0 args=0x10 locals=0x0
      0x0000 00000 (/tmp/foo/foo.go:4)        TEXT    "".popcnt(SB), $0-16
      0x0000 00000 (/tmp/foo/foo.go:4)        NOP
      0x0000 00000 (/tmp/foo/foo.go:4)        NOP
      0x0000 00000 (/tmp/foo/foo.go:4)        MOVQ    "".x+8(FP), AX
      0x0005 00005 (/tmp/foo/foo.go:4)        FUNCDATA        $0, gclocals·23e8278e2b69a3a75fa59b23c49ed6ad(SB)
      0x0005 00005 (/tmp/foo/foo.go:4)        FUNCDATA        $1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
      0x0005 00005 (/tmp/foo/foo.go:5)        MOVQ    $0, CX
      0x0007 00007 (/tmp/foo/foo.go:6)        CMPQ    AX, $0
      0x000b 00011 (/tmp/foo/foo.go:6)        JLS     $0, 35
      0x000d 00013 (/tmp/foo/foo.go:7)        MOVQ    AX, BX
      0x0010 00016 (/tmp/foo/foo.go:7)        ANDQ    $1, BX
      0x0014 00020 (/tmp/foo/foo.go:7)        ADDQ    CX, BX
      0x0017 00023 (/tmp/foo/foo.go:7)        MOVQ    BX, CX
      0x001a 00026 (/tmp/foo/foo.go:7)        NOP
      0x001a 00026 (/tmp/foo/foo.go:6)        SHRQ    $1, AX
      0x001d 00029 (/tmp/foo/foo.go:6)        NOP
      0x001d 00029 (/tmp/foo/foo.go:6)        CMPQ    AX, $0
      0x0021 00033 (/tmp/foo/foo.go:6)        JHI     $0, 13
      0x0023 00035 (/tmp/foo/foo.go:9)        MOVQ    CX, "".~r1+16(FP)
      0x0028 00040 (/tmp/foo/foo.go:9)        RET
      0x0000 48 8b 44 24 08 31 c9 48 83 f8 00 76 16 48 89 c3  H.D$.1.H...v.H..
      0x0010 48 83 e3 01 48 01 cb 48 89 d9 48 d1 e8 48 83 f8  H...H..H..H..H..
      0x0020 00 77 ea 48 89 4c 24 10 c3                       .w.H.L$..
  ```

**Comment by bchurchill** [comment]
We have a new release now available.  Here's a link to that: https://github.com/StanfordPL/stoke

Hopefully it will make things better and not worse!  In the meantime, I'm going to take your first bug and file it against x64asm.  The third one is already taken care of (the feature is still there, but it's now the default and called --no_relax_reg)..  Could you try reproducing the second one in the latest STOKE?  If you can, please file a bug in the new repository.

**Comment by bchurchill** [comment]
After looking at the first issue more carefully, I think it may also already be fixed in the latest x64asm which uses a totally different parser.  Can you confirm?

**Comment by ainar-g** [comment]
Thanks, but I cann't check it out because I have issues building the new version. I've filed [#836](https://github.com/StanfordPL/stoke/issues/836) in the new repo describing all that went wrong.
