### ISSUE TITLE
git clone issues

### ISSUE THREAD

**Issue by rknath** [eschkufz/stoke-release#7]
git clone https://github.com/eschkufz/stoke 
is prompting for username/pass 

git clone https://github.com/eschkufz/cpputil 
is working fine.. 

I am behind a proxy and I think I have the correct setup .. is there anything that you can do ?

**Comment by eschkufz** [comment]
Try git clone https://github.com/eschkufz/stoke-release?

**Comment by bchurchill** [comment]
I'm assuming this was resolved.  Let us know if you have further trouble with this.
